# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e101bc4509763ff05a96425c7b1e5ad497c750ac937c48393e34cfd93dc35092c16536826ee1b0aaf8b8908ab4ccf637b7137c3fa7365d758f35b58bd4303f8

test:
  secret_key_base: b84c006a0582289661bb08b2e076b16674112a1030ebb48e484ae3b3c26067be6bb9d9968997d1fbfec078ed03c2c49a838c097a4ed71cf3b21900a5125cdf98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
